// <auto-generated />
using System;
using E_COMMERCE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_COMMERCE.Migrations.Commerce2
{
    [DbContext(typeof(Commerce2Context))]
    [Migration("20250918130416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.Property<int?>("Quntity")
                        .HasColumnType("int");

                    b.Property<string>("Userid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("PK__cart__3213E83FEA864B3E");

                    b.HasIndex(new[] { "Productid" }, "IX_cart_productid");

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Cetogery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photos");

                    b.HasKey("Id");

                    b.ToTable("cetogery", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Cities__3214EC075BBBA51F");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Countrie__3214EC07B82D97EF");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Order1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("Onlinepaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07C861E642");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Orderdetial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Entitydata")
                        .HasColumnType("date")
                        .HasColumnName("entitydata");

                    b.Property<int?>("Order1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Orderid")
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<int?>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Totalprice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("totalprice");

                    b.HasKey("Id");

                    b.HasIndex("Order1Id");

                    b.HasIndex(new[] { "Orderid" }, "IX_orderdetials_orderid");

                    b.HasIndex(new[] { "Productid" }, "IX_orderdetials_productid");

                    b.ToTable("orderdetials", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ceito")
                        .HasColumnType("int")
                        .HasColumnName("ceito");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("Entitydata")
                        .HasColumnType("date")
                        .HasColumnName("entitydata");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photo");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<string>("Productquntity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productquntity");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Reviewurl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reviewurl");

                    b.Property<string>("Siplername")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("siplername");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ceito" }, "IX_product_ceito");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Productimage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<int?>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Productid" }, "IX_productimage_productid");

                    b.ToTable("productimage", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Review2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__review2__3214EC0702341674");

                    b.HasIndex(new[] { "ProductId" }, "IX_review2_ProductId");

                    b.ToTable("review2", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__States__3214EC075A231AEF");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("E_COMMERCE.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_COMMERCE.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("E_COMMERCE.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("E_COMMERCE.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("E_COMMERCE.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUserToken", b =>
                {
                    b.HasOne("E_COMMERCE.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Cart", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK_cart_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.City", b =>
                {
                    b.HasOne("E_COMMERCE.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__StateId__1EA48E88");

                    b.Navigation("State");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Order1", b =>
                {
                    b.HasOne("E_COMMERCE.Models.City", "City")
                        .WithMany("Order1s")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__CityId__245D67DE");

                    b.HasOne("E_COMMERCE.Models.Country", "Country")
                        .WithMany("Order1s")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__CountryI__22751F6C");

                    b.HasOne("E_COMMERCE.Models.State", "State")
                        .WithMany("Order1s")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__StateId__236943A5");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Orderdetial", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Order1", null)
                        .WithMany("Orderdetials")
                        .HasForeignKey("Order1Id");

                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Orderdetials")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK_orderdetials_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Product", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Cetogery", "CeitoNavigation")
                        .WithMany("Products")
                        .HasForeignKey("Ceito")
                        .HasConstraintName("FK_product_cetogery");

                    b.Navigation("CeitoNavigation");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Productimage", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Productimages")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK_productimage_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Review2", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Review2s")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.State", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__States__CountryI__1BC821DD");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("E_COMMERCE.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Cetogery", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_COMMERCE.Models.City", b =>
                {
                    b.Navigation("Order1s");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Country", b =>
                {
                    b.Navigation("Order1s");

                    b.Navigation("States");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Order1", b =>
                {
                    b.Navigation("Orderdetials");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orderdetials");

                    b.Navigation("Productimages");

                    b.Navigation("Review2s");
                });

            modelBuilder.Entity("E_COMMERCE.Models.State", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Order1s");
                });
#pragma warning restore 612, 618
        }
    }
}
