// <auto-generated />
using System;
using E_COMMERCE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_COMMERCE.Migrations.Commerce
{
    [DbContext(typeof(CommerceContext))]
    partial class CommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_COMMERCE.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.Property<int?>("Quntity")
                        .HasColumnType("int");

                    b.Property<int?>("Userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("PK__cart__3213E83FEA864B3E");

                    b.HasIndex("Productid");

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Cetogery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photos");

                    b.HasKey("Id");

                    b.ToTable("cetogery", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adderss")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adderss");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EntityDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<bool?>("Onlinepaid")
                        .HasColumnType("bit")
                        .HasColumnName("onlinepaid");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Orderdetial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Entitydata")
                        .HasColumnType("date")
                        .HasColumnName("entitydata");

                    b.Property<int?>("Orderid")
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<int?>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Totalprice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("totalprice");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Orderid" }, "IX_orderdetials_orderid");

                    b.HasIndex(new[] { "Productid" }, "IX_orderdetials_productid");

                    b.ToTable("orderdetials", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ceito")
                        .HasColumnType("int")
                        .HasColumnName("ceito");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("Entitydata")
                        .HasColumnType("date")
                        .HasColumnName("entitydata");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photo");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<string>("Productquntity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productquntity");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Reviewurl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reviewurl");

                    b.Property<string>("Siplername")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("siplername");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ceito" }, "IX_product_ceito");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Productimage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<int?>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Productid" }, "IX_productimage_productid");

                    b.ToTable("productimage", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Review2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__review2__3214EC0702341674");

                    b.HasIndex(new[] { "ProductId" }, "IX_review2_ProductId");

                    b.ToTable("review2", (string)null);
                });

            modelBuilder.Entity("E_COMMERCE.Models.Cart", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK_cart_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Orderdetial", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Order", "Order")
                        .WithMany("Orderdetials")
                        .HasForeignKey("Orderid")
                        .HasConstraintName("FK_orderdetials_order");

                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Orderdetials")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK_orderdetials_product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Product", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Cetogery", "CeitoNavigation")
                        .WithMany("Products")
                        .HasForeignKey("Ceito")
                        .HasConstraintName("FK_product_cetogery");

                    b.Navigation("CeitoNavigation");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Productimage", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Productimages")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK_productimage_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Review2", b =>
                {
                    b.HasOne("E_COMMERCE.Models.Product", "Product")
                        .WithMany("Review2s")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Cetogery", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Order", b =>
                {
                    b.Navigation("Orderdetials");
                });

            modelBuilder.Entity("E_COMMERCE.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orderdetials");

                    b.Navigation("Productimages");

                    b.Navigation("Review2s");
                });
#pragma warning restore 612, 618
        }
    }
}
